name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and run the Docker image
      run: >
        docker build . --tag danbeale/grid_solve:latest &&
        docker run --rm danbeale/grid-solve:latest
